server:
  port: 3344
spring:
  application:
    name: cloud-payment-service-hystrix
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    config:
      server:
        git:
          uri: https://github.com/liyichencc/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
      label: master
