server:
  port: 8009
spring:
  application:
    name: cloud-payment-service-hystrix

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    drivider-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  ribbon:
    # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
    ReadTimeout: 5000
    # 指的是建立连接后从服务器读取到可用资源所用的时间
    ConnectTimeout: 5000
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 30000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.study.entities  #所有entity别名所在包


