server:
  port: 80


spring:
  application:
    name: consul-consumer-payment-hystrix

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

